#!/bin/sh

if python3 -m unittest discover tests; then
    echo "All tests passed correctly"
    exit 0
else
    echo "Some tests have failed. Please correct your code before committing"
    exit 1
fi
